### ISSUE TITLE
Possibly missing index?

### ISSUE THREAD

**Issue by wasade** [dpear/q2-convexhull#1]
I'm receiving the following traceback when attempting a transform of the output of `convex_hull` to `pd.DataFrame`. I believe it suggest the returned dataframe is missing an index

```
Traceback (most recent call last):
  File "convexhull_beam.py", line 33, in <module>
    cv_16s_df = cv_16s_ar.view(pd.DataFrame)
  File "/home/mcdonadt/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/sdk/result.py", line 319, in view
    return self._view(view_type)
  File "/home/mcdonadt/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/sdk/result.py", line 331, in _view
    result = transformation(self._archiver.data_dir)
  File "/home/mcdonadt/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/core/transform.py", line 70, in transformation
    new_view = transformer(view)
  File "/home/mcdonadt/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/core/transform.py", line 214, in wrapped
    return transformer(view.file.view(self._wrapped_view_type))
  File "/home/mcdonadt/q2-convexhull/q2_convexhull/_transformer.py", line 19, in _2
    return Metadata.load(str(ff)).to_dataframe()
  File "/home/mcdonadt/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/metadata/metadata.py", line 357, in load
    return MetadataReader(filepath).read(into=cls,
  File "/home/mcdonadt/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/metadata/io.py", line 71, in read
    header = self._read_header()
  File "/home/mcdonadt/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/metadata/io.py", line 144, in _read_header
    raise MetadataFileError(
qiime2.metadata.io.MetadataFileError: Found unrecognized ID column name '' while searching for header. The first column name in the header defines the ID column, and must be one of these values:

Case-insensitive: 'feature id', 'feature-id', 'featureid', 'id', 'sample id', 'sample-id', 'sampleid'

Case-sensitive: '#OTU ID', '#OTUID', '#Sample ID', '#SampleID', 'sample_name'

NOTE: Metadata files must contain tab-separated values.

There may be more errors present in the metadata file. To get a full report, sample/feature metadata files can be validated with Keemei: https://keemei.qiime2.org

Find details on QIIME 2 metadata requirements here: https://docs.qiime2.org/2022.2/tutorials/metadata/
```

**Comment by dpear** [comment]
Hi @wasade ! The output of `convex_hull` is a `pd.DataFrame` so do you think the error could be coming from trying to convert something that is already a frame, similar to how an error is thrown with `pd.Series` types?

**Comment by wasade** [comment]
I was running this as a QIIME 2 action, so what I receive back is an Artifact. The exception was occurring when transforming the Artifact to a pd.DataFrame

**Comment by wasade** [comment]
Hey @dpear, is there a plan to fix this?

**Comment by dpear** [comment]
Let me take a look.

**Comment by wasade** [comment]
Thanks!

**Comment by dpear** [comment]
should work now!

**Comment by wasade** [comment]
I recommend constructing a regression test. It's not apparent to me from a review of the change set that the bug is fixed. For example, the approach I take with bugs on projects like BIOM is to (a) implement a unit test that reproduces the reported bug (b) run the test code to ensure I can reproduce the bug (c) fix the code (d) verify the code is fixed by assuring the test passes. This type of a approach is valuable for two reasons. First, we demonstrably solve the bug. Second, because the test is part of the test suite, we are protected from the bug accidentally occurring again (hence a regression test).
